version: "3.9"
services:
  fortio-client:
    image: boeboe/fortio
    ports:
      - "8080:8080"
  envoy-proxy:
    image: boeboe/envoy
    volumes:
      - ${PWD}/config/envoy.yaml:/etc/envoy/envoy.yaml
  fortio-server:
    image: boeboe/fortio
