version: "3.9"
services:
  fortio-client:
    image: boeboe/fortio
    ports:
      - "8080:8080"
  nginx-proxy:
    image: boeboe/nginx
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf
  fortio-server:
    image: boeboe/fortio
